org.gradle.jvmargs  = -Xmx3G
org.gradle.parallel = true

# Project properties
plugin-name         = Core
version             = 1.0.0-SNAPSHOT
description         = Core system of the Crystalixs minecraft network

# Plugin properties

# Format: Name bzw. Name1, Name2, ...
# Beispiel 1 (einzelner Author): authors = Autor
# Beispiel 2 (mehrere Autoren): authors = Autor, Autor2
authors             = MerryDev