package net.crystalixs.core.paper.home;

public enum HomeError {
    INVALID_NAME,
    INVALID_POSITION,
    HOME_ALREADY_EXISTS,
    HOME_NOT_FOUND,
    PLAYER_CREATION_FAILED,
    HOME_CREATION_FAILED,
    HOME_DELETION_FAILED,
    HOME_RENAME_FAILED,
    HOME_LIMIT_REACHED
}
